name: Deploy to Servers

on:
  push:
    branches: 
      - "main"
      - "Development(DO_NOT_REMOVE)"
  workflow_dispatch:

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install PM2 if not exists
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi

            # Navigate to web directory
            cd /var/www/html
            
            # Safely stop existing processes
            pm2 stop all || true
            pm2 delete all || true
            
            # Clone/pull repository
            if [ ! -d "Laravel-Vue-LMS" ]; then
              git clone https://github.com/nethsuka/Laravel-Vue-LMS.git
              cd Laravel-Vue-LMS
            else
              cd Laravel-Vue-LMS
              git fetch origin main
              git reset --hard origin/main
            fi
            
            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader
            
            # Install and build frontend assets
            npm ci
            npm uninstall flowbite flowbite-vue
            npm install flowbite@2.5.1 flowbite-vue@0.1.6
            npm run build
            
            # Set up Laravel environment
            cp .env.example .env
            php artisan key:generate --force
            php artisan storage:link --force
            
            # Set proper permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            # Create required directories
            mkdir -p storage/framework/{sessions,views,cache}
            
            # Start services using PM2
            pm2 start "php artisan serve --host=0.0.0.0 --port=8000" --name "laravel"
            pm2 start "npm run dev" --name "vite"
            
            echo "Production deployment completed successfully"

  deploy-development:
    if: github.ref == 'refs/heads/Development(DO_NOT_REMOVE)'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          port: 22
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            # Install PM2 if not exists
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              sudo npm install -g pm2
            fi

            # Navigate to web directory
            cd /var/www/html
            
            # Safely stop existing processes
            pm2 stop all || true
            pm2 delete all || true
            
            # Clone/pull repository with escaped branch name
            if [ ! -d "Laravel-Vue-LMS" ]; then
              git clone -b "Development(DO_NOT_REMOVE)" https://github.com/nethsuka/Laravel-Vue-LMS.git
              cd Laravel-Vue-LMS
            else
              cd Laravel-Vue-LMS
              git fetch origin "Development(DO_NOT_REMOVE)"
              git reset --hard "origin/Development(DO_NOT_REMOVE)"
            fi
            
            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader
            
            # Install and build frontend assets
            npm ci
            npm uninstall flowbite flowbite-vue
            npm install flowbite@2.5.1 flowbite-vue@0.1.6
            npm run build
            
            # Set up Laravel environment
            cp .env.example .env
            php artisan key:generate --force
            php artisan storage:link --force
            
            # Set proper permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            # Create required directories
            mkdir -p storage/framework/{sessions,views,cache}
            
            # Start services using PM2
            pm2 start "php artisan serve --host=0.0.0.0 --port=8000" --name "laravel"
            pm2 start "npm run dev" --name "vite"
            
            echo "Development deployment completed successfully"