name: Deploy to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to web directory
            cd /var/www/html
            
            # Safely stop existing processes
            pm2 stop all || true
            pm2 delete all || true
            
            # Clone/pull repository
            if [ ! -d "Laravel-Vue-LMS" ]; then
              git clone https://github.com/nethsuka/Laravel-Vue-LMS.git
              cd Laravel-Vue-LMS
            else
              cd Laravel-Vue-LMS
              git fetch origin main
              git reset --hard origin/main
            fi
            
            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader
            
            # Install and build frontend assets
            npm ci
            npm uninstall flowbite flowbite-vue
            npm install flowbite@2.5.1 flowbite-vue@0.1.6
            npm run build
            
            # Set up Laravel environment
            cp .env.example .env
            php artisan key:generate --force
            php artisan storage:link --force
            
            # Set proper permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            # Create required directories
            mkdir -p storage/framework/{sessions,views,cache}
            
            # Start services using PM2
            pm2 start "php artisan serve --host=0.0.0.0 --port=8000" --name "laravel"
            pm2 start "npm run dev" --name "vite"
            
            echo "Deployment completed successfully"