name: Deploy to Servers

on:
  push:
    branches: 
      - "main"
      - "Development(DO_NOT_REMOVE)"
  workflow_dispatch:

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install PM2 if not exists
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              sudo npm install -g pm2
            fi

            # Set up application directory with proper permissions
            sudo mkdir -p /var/www/html/Laravel-Vue-LMS
            sudo chown -R www-data:www-data /var/www/html/Laravel-Vue-LMS

            # Navigate to web directory
            cd /var/www/html/Laravel-Vue-LMS

            # Safely stop existing processes
            sudo pm2 stop all || true
            sudo pm2 delete all || true

            # Clone/pull repository
            if [ -d ".git" ]; then
              sudo git fetch origin main
              sudo git reset --hard origin/main
            else
              sudo git clone -b main git@github.com:nethsuka/Laravel-Vue-LMS.git .
            fi

            # Install dependencies with sudo
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader
            sudo npm install
            sudo npm uninstall flowbite flowbite-vue
            sudo npm install flowbite@2.5.1 flowbite-vue@0.1.6
            sudo npm run build

            # Laravel setup with sudo
            sudo cp .env.example .env
            sudo php artisan key:generate --force
            sudo php artisan storage:link --force

            # Create and set permissions for directories
            sudo mkdir -p storage/framework/{sessions,views,cache}
            sudo mkdir -p storage/logs
            sudo mkdir -p bootstrap/cache
            
            # Set proper permissions
            sudo chown -R www-data:www-data storage
            sudo chown -R www-data:www-data bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache
            sudo chown -R www-data:www-data node_modules
            sudo chown -R www-data:www-data public/build
            
            # PM2 operations
            sudo pm2 save
            sudo pm2 startup
            sudo pm2 start --name "laravel" "php artisan serve --host=0.0.0.0 --port=8000"
            sudo pm2 start --name "vite" "npm run dev"
            sudo pm2 save

            echo "Production deployment completed successfully"

  deploy-development:
    if: github.ref == 'refs/heads/Development(DO_NOT_REMOVE)'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          port: 22
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            # Install PM2 if not exists
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              sudo npm install -g pm2
            fi

            # Directory setup
            sudo mkdir -p /var/www/html/Laravel-Vue-LMS
            sudo chown -R www-data:www-data /var/www/html/Laravel-Vue-LMS
            cd /var/www/html/Laravel-Vue-LMS

            # Stop existing processes
            sudo pm2 stop all || true
            sudo pm2 delete all || true

            # Clear caches
            sudo php artisan cache:clear
            sudo php artisan config:clear
            sudo php artisan view:clear
            sudo rm -rf node_modules/.vite

            # Repository operations
            if [ -d ".git" ]; then
              sudo git fetch origin "Development(DO_NOT_REMOVE)"
              sudo git reset --hard "origin/Development(DO_NOT_REMOVE)"
            else
              sudo git clone -b "Development(DO_NOT_REMOVE)" git@github.com:nethsuka/Laravel-Vue-LMS.git .
            fi

            # Create directory structure
            sudo mkdir -p storage/framework/{views,sessions,cache}
            sudo mkdir -p storage/logs
            sudo mkdir -p bootstrap/cache

            # Install dependencies
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader
            sudo npm install
            sudo npm uninstall flowbite flowbite-vue
            sudo npm install flowbite@2.5.1 flowbite-vue@0.1.6
            sudo npm run build

            # Laravel setup
            sudo cp .env.example .env
            sudo php artisan key:generate --force
            sudo php artisan storage:link --force

            # Set permissions
            sudo chown -R www-data:www-data storage
            sudo chown -R www-data:www-data bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache
            sudo chown -R www-data:www-data node_modules
            sudo chown -R www-data:www-data public/build

            # Set log file permissions
            sudo touch storage/logs/laravel.log
            sudo chown www-data:www-data storage/logs/laravel.log
            sudo chmod 775 storage/logs/laravel.log

            # PM2 setup and start
            sudo pm2 save
            sudo pm2 startup
            sudo pm2 start --name "laravel" "php artisan serve --host=0.0.0.0 --port=8000" --time
            sudo pm2 start --name "vite" "npm run dev" --time
            sudo pm2 save

            echo "Development deployment completed successfully"